module.exports = {
  EVENT_NEW_USER: 'NEW_USER',
  EVENT_USER_CONFIRMED: 'USER_CONFIRMED',
  EVENT_SHOPPING_CARD_CREATED: 'SHOPPING_CARD_CREATED',
  EVENT_SHOPPING_CARD_ITEM_ADDED: 'SHOPPING_CARD_ITEM_ADDED',
  EVENT_SHOPPING_CARD_ITEM_REMOVED: 'SHOPPING_CARD_ITEM_REMOVED',
};



